version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:14
    restart: always
    env_file:
      - .env  
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: