name: CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'fastapi-hw/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "SQLALCHEMY_DATABASE_URL=${{ secrets.SQLALCHEMY_DATABASE_URL }}" >> .env

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Run docker-compose
        run: docker-compose up -d --build

      - name: Wait for services to start
        run: sleep 15

      - name: Check backend health
        run: curl -f https://nfactor.onrender.com

      - name: Show logs if failed
        if: failure()
        run: docker-compose logs
